
all:
	clang  -Wall -Werror -o lab2 lab2.c src/array.c src/math_func.c -Iinclude -lm

mp:
	clang  -Wall -Werror -o lab2-mp lab2.c src/array.c src/math_func.c -Iinclude -lm -fopenmp

clear:
	rm -rf lab2